# Generated by Django 3.2.7 on 2021-11-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Aluno',
        ),
    ]
